repository: acusp/AC-Navi
repository_url: https://github.com/acusp/AC-Navi
timezone: Asia/Shanghai
lang: zh_CN


title: 歧点导航 · AC-Navi
alias: 歧点导航
description: A Navigation Website for acusp.info
keywords: 歧点导航, AC-Navi acusp, Navi, Navigation
url: https://navi.acusp.info
logo: /images/favicon.ico


#author: acusp
#author_url: https://acusp.info
#organization:
#organization_url:
#contact: acusp.xu[at]gmail.com[dot]com


# Baidu Analytics
ba_track_id: ce472038c53a64826054bafc870d2d24
# Google Analytics
ga_track_id: 'UA-96564187-1'
ga_domain: acusp.info


plugins:
- jekyll-seo-tag
- jekyll-sitemap


exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
